package model;

import java.util.List;

 
import dao.ClienteDaoPostgreSqlDao;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projeto Integrado - SystemManagerRentalCar
//  @ File Name : Cliente.java
//  @ Date : 30/09/2013
//  @ Author : Marcus/Felipe/Reno/David/Phelipe/Orlando
//
//

/** */
public class Cliente {
	/** */
	protected String nome;
	
	/** */
	protected String telefone;
	protected int id;
	protected String tipo;
	
	public Cliente() {
		super();
		 
	}

	public Cliente(String nome, String telefone, String email, String endereco) {
		super();
		this.nome = nome;
		this.telefone = telefone;
		this.email = email;
		this.endereco = endereco;
	}

	public String getNome() {
		return nome;
	}
 
	 public int getId()
	 {
		 return id;
	 }
	 public void setId(int id)
	 {
		 this.id=id;
	 }
	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public String getEmail() {
		return email;
	}
     public String getTipo()
     {return tipo;}
     public void setTipo(String tipoCliente)
     {
    	 tipo= tipoCliente;
     }
	public void setEmail(String email) {
		this.email = email;
	}

	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	/** */
	protected String email;
	
	/** */
	protected String endereco;

	public List<Cliente> ObterClientes() {
		
		ClienteDaoPostgreSqlDao dao = new ClienteDaoPostgreSqlDao();
		
		return dao.obterCliente();
	}
	

}
