package model;

import java.util.List;

import dao.PessoaFisicaDao;
import model.PessoaFisica;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projeto Integrado - SystemManagerRentalCar
//  @ File Name : PessoaFisica.java
//  @ Date : 30/09/2013
//  @ Author : Marcus/Felipe/Reno/David/Phelipe/Orlando
//
//




/** */
public class PessoaFisica extends Cliente {
	/** */
	private String cpf;
	private String sexo;
	/** */
	private String rg;
	
	/** */
	private String dtNascimento;
	
	/** */
	private String cnh;
	
	/** */
	private String categoria;
	
	/** */
	private String dtValidade;
	
	/** */
	private String estadoEmissor;
	
	/** */
	private String passaporte;

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public String getRg() {
		return rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}

	public String getDtNascimento() {
		return dtNascimento;
	}

	public void setDtNascimento(String dtNascimento) {
		this.dtNascimento = dtNascimento;
	}

	public String getCnh() {
		return cnh;
	}

	public void setCnh(String cnh) {
		this.cnh = cnh;
	}

	public String getCategoria() {
		return categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public String getDtValidade() {
		return dtValidade;
	}

	public void setDtValidade(String dtValidade) {
		this.dtValidade = dtValidade;
	}

	public String getEstadoEmissor() {
		return estadoEmissor;
	}

	public void setEstadoEmissor(String estadoEmissor) {
		this.estadoEmissor = estadoEmissor;
	}

	public String getPassaporte() {
		return passaporte;
	}

	public void setPassaporte(String passaporte) {
		this.passaporte = passaporte;
	}

	public PessoaFisica(String cpf, String rg, String dtNascimento,
			String cnh, String categoria, String dtValidade,
			String estadoEmissor, String passaporte) {
		super();
		this.cpf = cpf;
		this.rg = rg;
		this.dtNascimento = dtNascimento;
		this.cnh = cnh;
		this.categoria = categoria;
		this.dtValidade = dtValidade;
		this.estadoEmissor = estadoEmissor;
		this.passaporte = passaporte;
	}

	public PessoaFisica() {
		super();
		// TODO Auto-generated constructor stub
	}

	public String getSexo() {
		// TODO Auto-generated method stub
		return sexo;
	}

	public String getDataValida() {
		// TODO Auto-generated method stub
		return dtValidade;
	}

	public void setSexo(String sexo) {
		// TODO Auto-generated method stub
		sexo = sexo;
	}

	 public  List<PessoaFisica> obterClientes (String nome, String cpf)
	 {
	    PessoaFisicaDao dao = new PessoaFisicaDao();
		return dao.obterClientesFisicos(nome,cpf);
	 }
	
	 public void Cadastrar()
	 {
		PessoaFisicaDao dao = new  PessoaFisicaDao();
		dao.cadastrar(this);
	 }

	public PessoaFisica getClienteFisicoById(int parseInt) {

     PessoaFisicaDao dao = new PessoaFisicaDao();
     
     return dao.getClienteFisicoById(parseInt);


	}

	public boolean Atualizar(PessoaFisica clienteFisico) {
	
		try{
			
			PessoaFisicaDao dao = new PessoaFisicaDao();
			dao.alterarClienteFisico(clienteFisico);
			
		}catch(Exception ex){
			
		 System.out.println(ex);
		 return false;
		 
		}
		
		
		return true;
	}

	public void Excluir(int id) {

		PessoaFisicaDao dao = new PessoaFisicaDao();
		dao.excluirClienteFisico(id);
	}


}
